export default {
  users: {},
  emojis: [
    ':rocket:',
    ':tada:',
    ':penguin:',
    ':robot:',
    ':hankey:',
    ':boom:',
    ':bento:',
    ':beers:',
    ':ambulance:',
    ':fire:',
    ':zap:',
    ':art:',
    ':checkered_flag:',
    ':hamburger:',
    ':feelsgood:',
    ':octocat:',
    ':squirrel:',
    ':skull:',
    ':musical_score:',
  ],
};
